# -*- coding: utf-8 -*-
"""Netflix_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WqYgkrZobr1RLrt1axvioXWvjbuT1YYO

#1. Defining Problem Statement and Analysing basic metrics (10 Points)

##Download the dataset and observe a subset of the data

**Importing Required Libraries**
"""

import numpy as np
import pandas as pd
import seaborn as sns

"""**Download the Netflix DataSet**"""

# !gdown https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/000/940/original/netflix.csv -O netflix_ds.csv
# df = pd.read_csv('netflix_ds.csv')
df = pd.read_csv(r"C:\Users\prath\Desktop\Prathamesh\Prathamesh\Learn\DSML\2 Common Core Foundations\Netflix_Project\DataSet\netflix.csv")
df.head()

"""#2. Observations on the shape of data, data types of all the attributes, conversion of categorical attributes to 'category' (If required), missing value detection, statistical summary (10 Points)

## Observe shape of data, data types of all the attributes
"""

df.info()

"""---
**Shape:**
- DataSet has `12 columns` (attributes)
- DataSet has `8807 data points`

**Data Type:**
- Attribute `release_year` is of `int64` Dtype
- `All the remaining atributes` are of `object` Dtype. 
---

##Numeric Variable (`release_year`): Missing value detection, statistical summary
"""

df.describe()

df['release_year'].isna().sum()

"""---
**Missing Values:**
- There are no missing Values
- There are no outliers like 0, -999, etc.

**Statistical Summary:**
- Data is from the year `1925` to `2021`
- Data Distribution
  - `50%` of the data is of the shows that are released `from 2017 till 2021` (~5 yrs)
  - `25%` of the data is of the shows that are released `from 2013 till 2017` (~4 yrs)
  - `25%` of the data is of the shows that are released `from 1925 till 2013` (~88 yrs)
---

#Non-Numeric Variables: Data Cleaning, Missing value detection, statistical summary, conversion of categorical attributes to 'category'

**Data Cleaning:**
- **Striping blank spaces** at the start and the end
- Treat blank spaces as missing values
"""

# Striping the values in Non-Numeric columns
df1 = df.drop('release_year', axis=1).apply(lambda x: x.str.rstrip()).apply(lambda x: x.str.lstrip())
# Assign to NaN
df1 = df1.apply(lambda series_: series_.apply(lambda value_: np.nan if value_=='' else value_))
# Update the DF
df[df1.columns] = df1
del df1
df.head()

"""**Misiing Values**"""

df.isna().sum()

"""---
`No missing values` in columns
- show_id
- type
- title
- listed_in
- description

Some columns have `missing values`
- dirctor:&emsp;&emsp;$\;$2634
- country:&emsp;&emsp;$\;\;$831
- cast:&emsp;&emsp;&emsp;&emsp;825
- date_added:&emsp;$\;$10
- rating:&emsp;&emsp;&emsp;&emsp;$\;$4
- duration:&emsp;&emsp;&emsp;$\;$3
---

**Statistical Summary**
"""

df.describe(include=object)

"""---
**show_id:**
- All the values are unique

**type:**
- It has two categories

**title:**
- There is a duplicate title: 'Consequences'

**director:**
- There are 4528 unique combination of directors
- Rajiv Chilaka alone has directed the most (19) shows

**cast:**
- There are 7692 unique combination of cast
- David Attenborough as a single cast has acted in the most (19) shows

**country:**
- Shows were produced in 748 different combinations of countries
- United States alone has produced the most (2818) shows

**date_added:**
- Out of 8797 available dates, there are 1714 unique date_added
- On January 1, 2020, most (110) shows were added

**rating:**
- There are 17 unique categories of rating
- Most (3207) shows have rating: TV-MA

**duration:**
- OUt of 8797 available durations, there are 220 unique durations
- Season 1 is the most repeated (1793) duration

**listed_in:**
- OUt of 8807 available genre combinations, there are 514 unique genre combinations
- Most of the shows (362) fall under 'Dramas, International Movies' Genre

**description:**
- Most of the shows have unique descriptions
---

**Conversion of Categorical Attributes to 'category'**

- Convert the show type column Dtype to category as it has two categoreis: Movie and TV Show
- Combine the ratings that have same meaning and create new ratings for the analysis. Then convert the rating Dtype to category
"""

# Convert show type to category Dtype
df['type'] = df['type'].astype('category')

# Combine ratings having same meaning
df.loc[df['rating'].isin(['TV-MA', 'R', 'NC-17']), 'rating'] = '17+'
df.loc[df['rating'].isin(['G', 'TV-G']), 'rating'] = 'General'
df.loc[df['rating'].isin(['NR', 'UR']), 'rating'] = 'Not Rated'
df.loc[df['rating']=='TV-Y', 'rating'] = 'All Kids'
df.loc[df['rating'].isin(['TV-PG', 'PG']), 'rating'] = 'Parental Guidance'
df.loc[df['rating']=='PG-13', 'rating'] = '13+'
df.loc[df['rating']=='TV-14', 'rating'] = '14+'
df.loc[df['rating'].isin(['TV-Y7', 'TV-Y7-FV']), 'rating'] = '7+'

# Convert rating column Dtype to category
df['rating'] = df['rating'].astype('category')

"""#5. Missing Value & Outlier check (Treatment optional) (10 Points)

##For Variable: director, cast and country

To find the best guess for the missing values, I tried to creat diffrent groups and observed for any pattern but I did not find any pattern.

Assign `missing director, cast and country` values as  `Unknown`
"""

df[['director', 'cast', 'country']] = df[['director', 'cast', 'country']].fillna('Unknown')

"""##For Variable: date_added

Convert the `date_added` column Dtype to `datetime`

To find the best guess for the missing date_added, I tried to creat diffrent groups and observed if ther is any pattern/ correlation with release date, type, directory, cast and country; but I could not find any.

Since missing date_added values are less in numbers (10). I would `keep it as NaN`. 

Check if the `date_added is before the release_year` of any show. If it is so, it is a wrong information. We are not sure if the release_year or date_added is correct. Therefore for such records we make those values `NaN`.
"""

df['date_added'] = pd.to_datetime(df['date_added'])

df.loc[df['date_added'].dt.year < df['release_year'], ['date_added', 'release_year']] = np.nan

"""##For Variable: duration"""

df.loc[df['duration'].isna()]

"""---
Duration values of the shows are shifted to rating columns.
Replace the duration from rating column to duration column

---
"""

df.loc[df['duration'].isna(), ['rating', 'duration']] = df.loc[df['duration'].isna(), ['duration', 'rating']].values

"""Recalculate `rating` categories"""

df['rating'] = df['rating'].astype('string')
df['rating'] = df['rating'].astype('category')

"""**Make the duration units uniform**
- Check different units available for type: Movie and TV Show
- Remove the units and convert the Dtype to Numeric

**For type: Movie**

check for different units used
"""

df.loc[df['type']=='Movie', 'duration'].str.split(' ').apply(lambda x: '-'.join([i for i in x if i.isalpha()])).unique()

"""---
All the durations of type Movie are in `min`

---

Check if all the values in the durtion column contains only one numeric value
"""

df.loc[df['type']=='Movie', 'duration'].str.split(' ').apply(lambda x: len([i for i in x if i.isnumeric()])==1).all()

"""Keep only the numeric values"""

df.loc[df['type']=='Movie', 'duration'] = df.loc[df['type']=='Movie', 'duration'].str.split(' ').apply(lambda x: [i for i in x if i.isnumeric()][0])

"""**For type: TV Show**

check for different units used
"""

df.loc[df['type']=='TV Show', 'duration'].str.split(' ').apply(lambda x: '-'.join([i for i in x if i.isalpha()])).unique()

"""---
All the durations of type TV Show are in either `Season` for 1 season and `Seasons` for multiple seasons

---

Check if all the values in the durtion column contains only one numeric value
"""

df.loc[df['type']=='TV Show', 'duration'].str.split(' ').apply(lambda x: len([i for i in x if i.isnumeric()])==1).all()

"""Keep only the numeric values"""

df.loc[df['type']=='TV Show', 'duration'] = df.loc[df['type']=='TV Show', 'duration'].str.split(' ').apply(lambda x: [i for i in x if i.isnumeric()][0])

"""**Convert the Dtype to integet**"""

df['duration'] = df['duration'].astype('int')

"""##For Variable: rating

Assign `Missing Rating` values to `Not Rated` Category
"""

df.loc[df['rating'].isna(), 'rating'] = 'Not Rated'

"""#Check for missing values"""

df.isna().sum()

"""---
As discussed, all the missing values are treated except the date_added column

---

#Check for outlier values
"""

df.groupby('type').describe()

df.groupby('type').describe(include=np.datetime64, datetime_is_numeric=True)

df.groupby('type').describe(include='category')

df.groupby('type')[['title', 'director', 'cast', 'country', 'listed_in']].describe(include=object)

"""---
Check Movies with title 'Consequences' as there are two movies with same title

---
"""

df.loc[df['title']=='Consequences']

"""Remove the duplicate movie record"""

df = df.drop_duplicates(subset='title')

"""#3. Non-Graphical Analysis: Value counts and unique attributes ​​(10 Points)

##Types of show (Movie/ TV Show); Unique Counts
"""

df['type'].value_counts()

(df['type'].value_counts()/ df.shape[0] * 100).round(2)

df.groupby('type')[['show_id', 'title']].nunique()

"""---
Columns `show_id` and `title` are `unique` for each show

There are `70% Movies` (6130) and `30% TV Shows` (2676)  

---

#Value Counts of Combination of Directors by Show Type
"""

df.loc[df['type']=='Movie', 'director'].value_counts()

df.loc[df['type']=='TV Show', 'director'].value_counts()

"""#Value Counts of Conbination of Cast by Show Type"""

df.loc[df['type']=='Movie', 'cast'].value_counts()

df.loc[df['type']=='TV Show', 'cast'].value_counts()

"""#Value Counts of Combination of Country by Show Type"""

df.loc[df['type']=='Movie', 'country'].value_counts()

df.loc[df['type']=='TV Show', 'country'].value_counts()

"""#Value Counts of Ratings by Show Type"""

df.loc[df['type']=='Movie', 'rating'].value_counts()

df.loc[df['type']=='TV Show', 'rating'].value_counts()

"""#Value Counts of Combinations of Gener by Show Type"""

df.loc[df['type']=='Movie', 'listed_in'].value_counts()

df.loc[df['type']=='TV Show', 'listed_in'].value_counts()

"""#Distribution of Date Added by Show Type"""

df.loc[df['type']=='Movie', 'date_added'].describe(datetime_is_numeric=True)

df.loc[df['type']=='TV Show', 'date_added'].describe(datetime_is_numeric=True)

"""#Distribution of Release Year by Show Type"""

df.loc[df['type']=='Movie', 'release_year'].describe().round()

df.loc[df['type']=='TV Show', 'release_year'].describe().round()

"""#Distribution of Duration by Show Type"""

df.loc[df['type']=='Movie', 'duration'].describe().round()

df.loc[df['type']=='TV Show', 'duration'].describe().round()

"""#4. Visual Analysis - Univariate, Bivariate after pre-processing of the data: Preprocessing

**Define a Function to Split Nested Data Column into Rows**
"""

def unnested_column(df, id_col, nested_col):
  df1 = pd.concat((df[id_col], df[nested_col].str.split(',', expand=True)), axis=1)
  df1 = pd.melt(df1.reset_index(), id_vars=['index', id_col], value_name=nested_col).dropna().sort_values('index').drop(['index', 'variable'], axis=1)
  df = pd.merge(df.drop(nested_col, axis=1), df1, on=id_col)
  return df

"""**Unnest director, cast, country and listed_in Columns**"""

df = unnested_column(df, 'show_id', 'director')
df = unnested_column(df, 'show_id', 'cast')
df = unnested_column(df, 'show_id', 'country')
df = unnested_column(df, 'show_id', 'listed_in')

"""**Rearrange the Columns**"""

df = df[['show_id', 'type', 'title', 'director', 'cast', 'country', 'listed_in', 'duration', 'rating', 'date_added', 'release_year', 'description']]

df.head(10)

"""#Testing"""

df.head()

df2 = pd.DataFrame({
    'col1': [' ', ' asdf', 'asd  ', np.nan, '  asdf  ', 'asdf', '', ''],
    'col2': [1, 2, 0, 4, 5, 6, 7, np.nan],
    'col3': ['1', '2', '0', '4', '5', '6', '7', '8']
})
df2

df2.loc[0,'col1'] is None

df2.apply(lambda x: x.apply(lambda y: np.nan if y=='' else y))

def blankToNan(col):
  return col.apply(lambda x: np.nan if x=='' else x)
df2.apply(lambda x: blankToNan(x))

df2.info()

df2.loc[:, 'col2'].isna().sum()

# df2['col1'].str.rstrip().isna()
# df2['col1'].str.rstrip().reset_index(drop=True)
df2.drop('col2', axis=1).apply(lambda x: x.str.rstrip()).info()

# df.loc[0, 'title'] = '    '+df.loc[0, 'title']+'    '
# df.loc[0, 'title']

df.loc[0][2][0]

